### ISSUE TITLE
remaining code and dataset

### ISSUE THREAD

**Issue by EverNorif** [Dou-Yiming/TaRF#1]
Hello, 

I am interested in this project, and I noticed that some parts of the code have already been uploaded, which is very exciting. Will the remaining code and related TaRF dataset be open source? If so, could you kindly share any information on when this might be available?
Thank you!

**Comment by Dou-Yiming** [comment]
Thanks for your interest! We are working on packaging the dataset and cleaning up the code now, and will let you know once it's released!

**Comment by nick1392** [comment]
Hi, do you have any update/tentative release date? Thank you so much!

**Comment by Dou-Yiming** [comment]
Hi! We are planning to finish it by the end of July! Will let you know once it's finished.

**Comment by Dou-Yiming** [comment]
Thanks for your patience!
The dataset is out here: https://www.dropbox.com/scl/fo/xusq5gvwauwakred27q9o/AHfcGs56Dv1ZCeitEM3-8_A?rlkey=07efzqehs918no80yi4jrokvh&st=0g4s2ioy&dl=0
We are still working on releasing the checkpoints, which will be out soon!

**Comment by EverNorif** [comment]
Thanks！
